import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: 'rgb(250, 250, 250)',
  },
  inputBox: {
    position: 'relative',
  },
  search: {
    position: 'absolute',
    top: 10,
    left: 10,
  },
  inputHome: {
    marginBottom: 20,
    paddingLeft: 35,
    paddingRight: 5,
    paddingVertical: 5,
    backgroundColor: 'rgb(255, 255, 255)',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'rgb(150, 150, 150)',
  },
  buttonAdd: {
    position: 'absolute',
    right: 20,
    bottom: 30,
  },
  title: {
    color: 'rgb(100, 100, 100)',
    fontSize: 40,
    marginBottom: 5,
    textAlign: 'center',
  },
  sellerBox: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    marginTop: 30,
    marginBottom: 'auto',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  nameSeller: {
    color: 'rgb(100, 100, 100)',
    fontSize: 20,
    marginBottom: 5,
  },
  phoneSeller: {
    color: 'rgb(100, 100, 100)',
    fontSize: 15,
  },
  imageSeller: {
    width: 70,
    height: 70,
    borderRadius: 70,
  },
  flexRowBox: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 10,
  },
  linkAuth: {
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    color: 'green',
  },
  imageBox: {
    minWidth: 300,
    height: 200,
    display: 'flex',
    flexDirection: 'row',
    gap: 5,
  },
  card: {
    position: 'relative',
    marginBottom: 10,
    marginHorizontal: 20,
    padding: 10,
    backgroundColor: '#ffffff',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,
    elevation: 5,
    overflow: 'hidden',
  },
  cardContainer: {
    flexDirection: 'row',
  },
  productTitle: {
    color: 'rgb(100, 100, 100)',
    fontSize: 16,
  },
  image: {
    width: 60,
    height: 50,
    marginRight: 5,
  },
  price: {
    fontSize: 15,
    color: 'green',
    position: 'absolute',
    top: 5,
    right: 10,
  },
  description: {
    fontSize: 12,
    marginTop: 10,
  },
  imageBoxProfile: {
    display: 'flex',
    alignItems: 'center',
  },
  btnEdit: {
    position: 'absolute',
    bottom: 5,
    right: -10,
    backgroundColor: 'green',
    width: 50,
    height: 50,
    padding: 5,
    borderRadius: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 120,
  },

  textArena: {
    borderColor: 'rgb(150, 150, 150)',
    borderWidth: 1,
    borderRadius: 5,
    marginTop: 5,
    padding: 3,
  },
  text: {
    color: 'rgb(100, 100, 100)',
    fontSize: 15,
    marginBottom: 5,
  },
});
